/**
 * The connector catalogue on `/admin/integrations`, transcribed from the live
 * "Available connectors" grid — every name, auth chip and description, in the
 * order the page lists them.
 */

export type ConnectorAuth = 'basic' | 'oauth2' | 'api_key' | 'none'

export type Connector = {
  id: string
  name: string
  auth: ConnectorAuth
  blurb: string
}

const c = (id: string, name: string, auth: ConnectorAuth, blurb = ''): Connector => ({ id, name, auth, blurb })

export const connectors: Connector[] = [
  c('smtp', 'Email (SMTP)', 'basic', 'Send email via any SMTP relay: Gmail, Office365, SendGrid, AWS SES, Mailgun, Postmark, or self-hosted Postfix.'),
  c('ftp', 'FTP / FTPS', 'basic', 'Transfer files to and from an FTP or FTPS (FTP over TLS) server. SFTP is a different protocol — use the SFTP connector (coming soon).'),
  c('google', 'Google (Gmail / Drive / Docs / Sheets / Slides / Forms / Calendar / YouTube)', 'oauth2', "Gmail, Drive/Files, Docs, Sheets, Slides, Forms, Calendar, YouTube and Cloud Translation using a user's Google account via OAuth 2.0."),
  c('hubspot', 'HubSpot', 'api_key', 'Create and update contacts, deals, and companies in HubSpot CRM via a Private App token.'),
  c('jira', 'Jira', 'api_key', 'Create / update / query issues and comments in Atlassian Jira Cloud.'),
  c('m365', 'Microsoft 365 (Outlook / Teams / OneDrive / SharePoint)', 'oauth2', "Outlook mail & calendar, Teams, OneDrive + Office files (Word / Excel / PowerPoint), SharePoint, OneNote and Bookings using a user's Microsoft 365 account via OAuth 2.0 (Graph API)."),
  c('postgres', 'PostgreSQL', 'basic', 'Run SELECT / INSERT / UPDATE / DELETE against a PostgreSQL database. Works with AWS RDS, Aurora, CloudSQL, Supabase, Neon, self-hosted.'),
  c('s3', 'Amazon S3', 'api_key', 'Upload, download, list and delete objects in S3 or any S3-compatible store (MinIO, Wasabi, B2, DigitalOcean Spaces).'),
  c('sap-odata', 'SAP OData', 'api_key', 'Read and write SAP business objects via the Gateway OData service (S/4HANA Cloud, S/4HANA On-Premise, ECC with SAP Gateway). Supports Basic auth + OAuth2 client-credentials.'),
  c('sharepoint', 'SharePoint', 'api_key', 'Upload, download and list files on a Microsoft SharePoint site (Graph API, app-only auth).'),
  c('slack', 'Slack', 'api_key', 'Post messages, upload files, and read channels from a Slack workspace.'),
  c('sap-rfc', 'SAP RFC (ECC / S4 on-premise)', 'basic', 'Read SAP tables and call BAPIs over classic RFC — the protocol on-premise ECC systems actually expose, no SAP Gateway or OData service required.'),
  c('hyperverge', 'Hyperverge KYC', 'api_key', 'PAN / Aadhaar / GST / passport / DL / face-match KYC via Hyperverge.'),
  c('idfy', 'IDfy KYC', 'api_key', 'PAN / Aadhaar / GST / passport / DL / face-match / OFAC + PEP screening / bank-account match via IDfy.'),
  c('cibil', 'CIBIL Credit Bureau', 'api_key', 'CIBIL (TransUnion India) — score, full report, enquiry history, delinquencies, identity match, dispute check.'),
  c('experian', 'Experian Credit Bureau', 'api_key', 'Experian — score, report, enquiries, identity match, dispute check.'),
  c('hapi-fhir', 'HAPI FHIR (generic)', 'oauth2', 'Vanilla FHIR R4 connector — Patient, Encounter, Claim, Coverage, Observation, Condition, eligibility check.'),
  c('epic-fhir', 'Epic FHIR', 'oauth2', 'Epic SMART-on-FHIR (R4) — Patient, Encounter, Claim, Coverage, Observation, Condition, eligibility check.'),
  c('delhivery', 'Delhivery', 'api_key'),
  c('bluedart', 'Blue Dart', 'api_key'),
  c('shiprocket', 'Shiprocket', 'api_key'),
  c('nic-irp', 'NIC e-Invoice (IRP)', 'api_key'),
  c('vibe-rpa', 'Vibe RPA Bot', 'none', 'Run a Vibe Studio automation bot as a step in any workflow. Generated by chat in Vibe Studio, callable via canvas here.'),
  c('zoho-people', 'Zoho People', 'oauth2', "Read employee records from Zoho People (HR) using a tenant's Zoho account via OAuth 2.0."),
  // The live card truncates mid-sentence; the tail is completed here.
  c('essl', 'ESSL Etimetracklite biometric', 'api_key', "Reference adapter for ESSL Etimetracklite biometric attendance devices. Runs in the Tenant Runner for on-prem deployments; polls the ESSL server, resolves biometric IDs to employees via the device's bindings, and pushes punches into Time & Attendance."),
  c('linkedin', 'LinkedIn', 'oauth2', 'Publish to a LinkedIn member profile via OAuth 2.0 (CRM Growth Engine).'),
  c('meta', 'Meta (Facebook & Instagram)', 'oauth2', 'Publish to Facebook Pages and Instagram business accounts via OAuth 2.0 (CRM Growth Engine).'),
]

export const connectorById = Object.fromEntries(connectors.map((item) => [item.id, item]))

/** Connectors whose auth is an OAuth 2.0 client the tenant has to register. */
export const oauthConnectors = connectors.filter((item) => item.auth === 'oauth2')

export const authLabel: Record<ConnectorAuth, string> = {
  basic: 'basic',
  oauth2: 'oauth2',
  api_key: 'api_key',
  none: 'none',
}
