-- 0001 — identity, tenancy, sessions, audit, outbox.
--
-- Conventions established here and relied on by every later migration:
--   * ids            uuid, generated by the database, never by the client
--   * time           timestamptz always; `date` only for calendar-day facts
--   * money          numeric(18,4) plus an explicit ISO-4217 currency column.
--                    Never float: 0.1 + 0.2 must not drift in an invoice total.
--   * tenancy        every business table carries tenant_id and cascades from it
--   * history        archived_at, not DELETE, wherever an audit trail must survive
--   * email          stored as given, compared case-insensitively via a lower() index
--                    (citext is an extension; a functional index is portable)

create table users (
  id                 uuid primary key default gen_random_uuid(),
  email              text        not null,
  full_name          text        not null,
  -- Null for an identity that exists only through an OAuth provider, so a
  -- provider-only account cannot be taken over by guessing a blank password.
  password_hash      text,
  email_verified_at  timestamptz,
  status             text        not null default 'active'
                       check (status in ('active', 'suspended', 'deleted')),
  last_login_at      timestamptz,
  failed_logins      integer     not null default 0,
  locked_until       timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create unique index users_email_lower_key on users (lower(email));

create table tenants (
  id            uuid primary key default gen_random_uuid(),
  name          text        not null,
  slug          text        not null,
  -- Tenant-level default; each company may override with its own currency.
  currency      char(3)     not null default 'USD',
  timezone      text        not null default 'UTC',
  status        text        not null default 'active'
                  check (status in ('active', 'suspended', 'closed')),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create unique index tenants_slug_key on tenants (lower(slug));

-- Legal entities inside a tenant. The prototype's Companies + intercompany
-- pairs screens need a real hierarchy, not a flat list.
create table companies (
  id             uuid primary key default gen_random_uuid(),
  tenant_id      uuid        not null references tenants (id) on delete cascade,
  parent_id      uuid        references companies (id) on delete restrict,
  name           text        not null,
  code           text        not null,
  currency       char(3)     not null,
  timezone       text        not null default 'UTC',
  country        text,
  tax_id         text,
  is_primary     boolean     not null default false,
  archived_at    timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create unique index companies_tenant_code_key on companies (tenant_id, lower(code));
create index companies_tenant_idx on companies (tenant_id);
create index companies_parent_idx on companies (parent_id);
-- At most one primary company per tenant, enforced by the database rather than
-- by whichever screen happens to set the flag.
create unique index companies_one_primary on companies (tenant_id) where is_primary;

create table memberships (
  id           uuid primary key default gen_random_uuid(),
  tenant_id    uuid        not null references tenants (id) on delete cascade,
  user_id      uuid        not null references users (id) on delete cascade,
  role         text        not null
                 check (role in ('owner', 'admin', 'member', 'viewer')),
  status       text        not null default 'active'
                 check (status in ('active', 'suspended')),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create unique index memberships_tenant_user_key on memberships (tenant_id, user_id);
create index memberships_user_idx on memberships (user_id);
-- A tenant must never lose its last owner; enforced in the service layer with a
-- locking read, because a partial index cannot express "at least one".

create table sessions (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid        not null references users (id) on delete cascade,
  -- Only the SHA-256 of the opaque token is stored. A database leak therefore
  -- does not hand the attacker usable session cookies.
  token_hash     text        not null,
  -- The tenant this session is currently acting in. Switching tenants rotates
  -- the row rather than trusting a tenant id from the client.
  tenant_id      uuid        references tenants (id) on delete cascade,
  issued_at      timestamptz not null default now(),
  last_seen_at   timestamptz not null default now(),
  expires_at     timestamptz not null,
  revoked_at     timestamptz,
  ip             text,
  user_agent     text,
  created_at     timestamptz not null default now()
);
create unique index sessions_token_hash_key on sessions (token_hash);
create index sessions_user_idx on sessions (user_id);
create index sessions_expiry_idx on sessions (expires_at) where revoked_at is null;

-- One table for every short-lived single-use token: verification, reset,
-- invitation acceptance. Same hashing and expiry rules apply to all of them,
-- so they should not be three near-identical tables that drift apart.
create table auth_tokens (
  id            uuid primary key default gen_random_uuid(),
  purpose       text        not null
                  check (purpose in ('email_verify', 'password_reset', 'invitation', 'mfa_enroll')),
  token_hash    text        not null,
  user_id       uuid        references users (id) on delete cascade,
  tenant_id     uuid        references tenants (id) on delete cascade,
  email         text,
  payload       jsonb       not null default '{}'::jsonb,
  expires_at    timestamptz not null,
  consumed_at   timestamptz,
  created_at    timestamptz not null default now()
);
create unique index auth_tokens_hash_key on auth_tokens (token_hash);
create index auth_tokens_user_idx on auth_tokens (user_id, purpose);

create table invitations (
  id            uuid primary key default gen_random_uuid(),
  tenant_id     uuid        not null references tenants (id) on delete cascade,
  email         text        not null,
  role          text        not null check (role in ('owner', 'admin', 'member', 'viewer')),
  invited_by    uuid        references users (id) on delete set null,
  status        text        not null default 'pending'
                  check (status in ('pending', 'accepted', 'revoked', 'expired')),
  accepted_by   uuid        references users (id) on delete set null,
  accepted_at   timestamptz,
  expires_at    timestamptz not null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
-- One live invitation per address per tenant; re-inviting reuses or replaces it.
create unique index invitations_tenant_email_pending
  on invitations (tenant_id, lower(email)) where status = 'pending';
create index invitations_tenant_idx on invitations (tenant_id);

-- Append-only. No update or delete grant is ever issued on this table, and the
-- actor is taken from the server session, never from a request body.
create table audit_events (
  id             bigserial primary key,
  tenant_id      uuid        references tenants (id) on delete cascade,
  company_id     uuid        references companies (id) on delete set null,
  actor_user_id  uuid        references users (id) on delete set null,
  actor_kind     text        not null default 'user'
                   check (actor_kind in ('user', 'system', 'job', 'integration', 'portal')),
  action         text        not null,
  resource       text        not null,
  resource_id    text,
  outcome        text        not null default 'success'
                   check (outcome in ('success', 'failure', 'denied')),
  -- before/after are redacted by the writer; this column must never hold a
  -- password, token or provider secret.
  detail         jsonb       not null default '{}'::jsonb,
  request_id     text,
  ip             text,
  occurred_at    timestamptz not null default now()
);
create index audit_tenant_time_idx on audit_events (tenant_id, occurred_at desc);
create index audit_resource_idx on audit_events (tenant_id, resource, resource_id);

-- Transactional outbox: a side effect is committed in the same transaction as
-- the state change that justifies it, then delivered at least once by a
-- dispatcher. Without this, "email sent" and "record saved" can disagree.
create table outbox (
  id              bigserial primary key,
  tenant_id       uuid        references tenants (id) on delete cascade,
  topic           text        not null,
  payload         jsonb       not null,
  -- Deduplicates retries of the same logical effect across dispatcher restarts.
  idempotency_key text,
  status          text        not null default 'pending'
                    check (status in ('pending', 'inflight', 'delivered', 'failed', 'dead')),
  attempts        integer     not null default 0,
  max_attempts    integer     not null default 8,
  available_at    timestamptz not null default now(),
  locked_by       text,
  locked_until    timestamptz,
  last_error      text,
  delivered_at    timestamptz,
  created_at      timestamptz not null default now()
);
create unique index outbox_idempotency_key on outbox (topic, idempotency_key)
  where idempotency_key is not null;
create index outbox_claim_idx on outbox (status, available_at) where status in ('pending', 'inflight');

-- Idempotency for inbound mutations: the same key replays the stored response
-- instead of performing the effect twice.
create table idempotency_keys (
  id              uuid primary key default gen_random_uuid(),
  tenant_id       uuid        references tenants (id) on delete cascade,
  user_id         uuid        references users (id) on delete set null,
  key             text        not null,
  endpoint        text        not null,
  request_hash    text        not null,
  status_code     integer,
  response_body   jsonb,
  completed_at    timestamptz,
  created_at      timestamptz not null default now(),
  expires_at      timestamptz not null
);
create unique index idempotency_scope_key on idempotency_keys (coalesce(tenant_id, '00000000-0000-0000-0000-000000000000'::uuid), endpoint, key);
